### ISSUE TITLE
task2

### ISSUE THREAD

**Issue by oksanaivanovaa** [oksanaivanovaa/1sem_PythonProgramming_HWs#3]
2nd home work is done

**Comment by oksanaivanovaa** [comment]
Thanks for comments!

**Comment by oksanaivanovaa** [comment]
I corrected this.
Competition: second part was fixed.
goodPairs: I added zero checking (i+j != 0)

There are the last pep8 error that I can't fix: E127 continuation line over-indented for visual indent. I don't understand what he wants from me...

**Comment by YakutovDmitriy** [comment]
Unfortunately this functions still don't work. Please find tests below:
* `competition`: `[9, 7, 4, 1, 1], 3`
* `goodPairs`: `[36, 15, 23, 15], [49, 30]`

**Comment by oksanaivanovaa** [comment]
Ok, I uploaded new commit
competition: cycle for from k+1 to len(e) instead of (len(e)-1)
goodPairs: set(a) and set(b) instead of just a and b

**Comment by YakutovDmitriy** [comment]
* `competition` is ok!
* `goodPairs`. I think You've recognized the problem. But the way you chose to solve it is incorrect. One more test for you: `[16, 25, 45, 30], [30, 16, 34, 45, 30]`
* `pep8`. I forgot to answer at previous time. Now he tells you about line 84. This line is continuation of the previous line. He tells you that indentation in this line should be different (4 symbols more than the previous line)

**Comment by oksanaivanovaa** [comment]
And again.

**Comment by YakutovDmitriy** [comment]
Ok!
